# Generated by Django 4.0.5 on 2022-09-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0003_remove_song_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
