# Generated by Django 4.0.5 on 2022-09-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0004_rename_tags_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
