# Generated by Django 4.0.5 on 2022-09-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='desc',
            field=models.CharField(default='Best banger on this site', max_length=124),
        ),
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
