# Generated by Django 4.0.5 on 2022-09-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0007_song_desc_song_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(default=None, upload_to='Songcovers'),
        ),
        migrations.AlterField(
            model_name='song',
            name='ost',
            field=models.FileField(upload_to='Songs'),
        ),
    ]
