# Generated by Django 4.0.5 on 2022-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0011_alter_song_price_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='Buy this man', max_length=124),
        ),
    ]
