# Generated by Django 4.0.5 on 2022-09-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0016_remove_song_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ostPlaceApi.tag'),
        ),
    ]
