# Generated by Django 4.0.5 on 2022-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0018_remove_song_tags_song_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(to='ostPlaceApi.tag'),
        ),
    ]
