# Generated by Django 4.0.5 on 2022-09-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0019_alter_song_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
    ]
