# Generated by Django 4.0.5 on 2022-09-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0020_remove_song_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(to='ostPlaceApi.tag'),
        ),
    ]
