# Generated by Django 4.0.5 on 2022-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0021_song_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='ostPlaceApi.tag'),
        ),
    ]
