# Generated by Django 4.0.5 on 2022-10-13 06:57

from django.db import migrations, models
import ostPlaceApi.models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0023_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(default=None, upload_to=ostPlaceApi.models.upload_announcement_image),
        ),
        migrations.AlterField(
            model_name='song',
            name='ost',
            field=models.FileField(upload_to=ostPlaceApi.models.upload_announcement_ost),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='OSTPlaceDefault.png', upload_to=ostPlaceApi.models.upload_avatar),
        ),
    ]
