# Generated by Django 4.0.5 on 2022-10-26 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0028_alter_basketost_ost_alter_basketost_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketost',
            name='OST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OST', to='ostPlaceApi.song'),
        ),
    ]
