# Generated by Django 4.0.5 on 2022-10-26 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0029_alter_basketost_ost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketost',
            name='OST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostPlaceApi.song'),
        ),
    ]
