# Generated by Django 4.0.5 on 2022-10-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0030_alter_basketost_ost'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
