# Generated by Django 4.1 on 2022-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0031_song_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('ost',)},
        ),
        migrations.RemoveField(
            model_name='song',
            name='bought',
        ),
    ]
