# Generated by Django 4.1 on 2022-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0032_song_status_alter_song_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
