# Generated by Django 4.1 on 2022-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0034_alter_useraccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
