# Generated by Django 4.1 on 2023-04-07 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ostPlaceApi', '0039_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='leaguePoints',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='FreestyleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.PositiveIntegerField(blank=True, null=True)),
                ('slots', models.PositiveIntegerField(default=5)),
                ('title', models.CharField(default='Everyone are welcome', max_length=128)),
                ('requirement', models.PositiveIntegerField(default=0)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomAdmin', to=settings.AUTH_USER_MODEL)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
