# Generated by Django 4.0.5 on 2022-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0002_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='desc',
        ),
    ]
