# Generated by Django 4.0.5 on 2022-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0010_alter_song_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=124),
        ),
    ]
