# Generated by Django 4.1 on 2022-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostPlaceApi', '0036_alter_useraccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
